# This is a basic workflow to help you get started with Actions

name: Sync Unity Cloud to GitHub


# Controls when the workflow will run
on:
  workflow_dispatch: # Запуск вручную
  schedule:
    - cron: '0 * * * *' # Каждый час (можно изменить)
  # Triggers the workflow on push or pull request events but only for the "main" branch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync:
    # The type of runner that the job will run on
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Полная история коммитов
      - name: Download from Unity Cloud
        env:
          UNITY_API_KEY: ${{ secrets.UNITY_CLOUD_API_KEY }}
          ORG_ID: "7972054929240" # ID организации в Unity Cloud
          PROJECT_ID: "1239c6ed-1d46-47ea-ad4d-e8eab0e905f7" # ID проекта в Unity Cloud
          BUILD_TARGET: "windows" # Например, "android", "ios", "webgl"
        run: |
          curl -H "Authorization: Bearer $UNITY_API_KEY" \
          "https://cloud-api.unity.com/v1/orgs/$ORG_ID/projects/$PROJECT_ID/buildtargets
          
          BUILD_DATA=$(curl -s -H "Authorization: Bearer $UNITY_API_KEY" \
            "https://cloud-api.unity.com/v1/orgs/$ORG_ID/projects/$PROJECT_ID/buildtargets/$BUILD_TARGET/builds?perPage=1&latest=true")

          # Извлекаем URL артефакта
          DOWNLOAD_URL=$(echo $BUILD_DATA | jq -r '.builds[0].links.download_primary.href')

          # Скачиваем и распаковываем (если архив)
          curl -L -o latest_build.zip "$DOWNLOAD_URL"
          unzip -o latest_build.zip -d ./temp_build
          rm latest_build.zip

          # Копируем изменения в проект
          cp -r ./temp_build/* ./
          rm -rf ./temp_build
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-sync from Unity Cloud"
          git push
     
