name: Sync Unity Cloud to GitHub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download from Unity Cloud
        env:
          UNITY_API_KEY: ${{ secrets.UNITY_CLOUD_API_KEY }}
          ORG_ID: "7972054929240"
          PROJECT_ID: "1239c6ed-1d46-47ea-ad4d-e8eab0e905f7"
          BUILD_TARGET: "windows"
        run: |
          # First request to check build targets
          curl -H "Authorization: Bearer $UNITY_API_KEY" \
            "https://cloud-api.unity.com/v1/orgs/$ORG_ID/projects/$PROJECT_ID/buildtargets"
          
          # Get latest build data
          BUILD_DATA=$(curl -s -H "Authorization: Bearer $UNITY_API_KEY" \
            "https://cloud-api.unity.com/v1/orgs/$ORG_ID/projects/$PROJECT_ID/buildtargets/$BUILD_TARGET/builds?perPage=1&latest=true")

          # Extract download URL
          DOWNLOAD_URL=$(echo "$BUILD_DATA" | jq -r '.builds[0].links.download_primary.href')

          # Download and unzip
          curl -L -o latest_build.zip "$DOWNLOAD_URL"
          unzip -o latest_build.zip -d ./temp_build
          rm latest_build.zip

          # Copy files
          cp -r ./temp_build/* ./
          rm -rf ./temp_build

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-sync from Unity Cloud"
            git push
          fi
