name: Sync Unity Cloud to GitHub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Every hour

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Download from Unity Cloud
        env:
          UNITY_API_KEY: "ee7885f5feb094fac060dffcb6c6c024"
          ORG_ID: "7972054929240"
          PROJECT_ID: "1239c6ed-1d46-47ea-ad4d-e8eab0e905f7"
          BUILD_TARGET: "standalonewindows"
        run: |
          # Debug: Check API key
          if [ -z "$UNITY_API_KEY" ]; then
            echo "❌ ERROR: UNITY_API_KEY is empty!"
            exit 1
          fi

          # Fetch latest build
          BUILD_DATA=$(curl -s -H "Authorization: Bearer $UNITY_API_KEY" \
            "https://build-api.cloud.unity3d.com/api/v1/orgs/$ORG_ID/projects/$PROJECT_ID/buildtargets/$BUILD_TARGET/builds?perPage=1&latest=true")

          # Check for errors
          if echo "$BUILD_DATA" | jq -e '.error' > /dev/null; then
            echo "❌ API Error: $(echo "$BUILD_DATA" | jq -r '.error')"
            exit 1
          fi

          DOWNLOAD_URL=$(echo "$BUILD_DATA" | jq -r '.builds[0].links.download_primary.href')
          echo "Downloading from: $DOWNLOAD_URL"

          # Download & extract
          curl -L -o latest_build.zip "$DOWNLOAD_URL"
          unzip -o latest_build.zip -d ./temp_build
          rm latest_build.zip

          # Copy files
          cp -r ./temp_build/* ./
          rm -rf ./temp_build

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if git diff --quiet && git diff --staged --quiet; then
            echo "✅ No changes to commit."
          else
            git commit -m "Auto-sync from Unity Cloud"
            git push
          fi
